package view;

import view.user.signUpPage;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import view.admin.mainAdminPage;
import view.user.mainPage;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author chemlleijoseph
 */
public class loginPage extends javax.swing.JFrame {

    /**
     * Creates new form loginPage
     */
    public loginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        userField5 = new javax.swing.JTextField();
        passField5 = new javax.swing.JPasswordField();
        usernameLabel5 = new javax.swing.JLabel();
        passLabel5 = new javax.swing.JLabel();
        exitButton5 = new javax.swing.JLabel();
        submitButton5 = new javax.swing.JLabel();
        signUpButton5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        userField6 = new javax.swing.JTextField();
        passField6 = new javax.swing.JPasswordField();
        usernameLabel6 = new javax.swing.JLabel();
        passLabel6 = new javax.swing.JLabel();
        exitButton6 = new javax.swing.JLabel();
        submitButton6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(176, 216, 251));

        userField5.setName(""); // NOI18N
        userField5.setOpaque(true);
        userField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userField5FocusGained(evt);
            }
        });

        passField5.setOpaque(true);
        passField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passField5FocusGained(evt);
            }
        });
        passField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passField5ActionPerformed(evt);
            }
        });

        usernameLabel5.setText("User Name");

        passLabel5.setText("Password");

        exitButton5.setText("X");
        exitButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });

        submitButton5.setBackground(new java.awt.Color(255, 255, 255));
        submitButton5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        submitButton5.setText("Submit");
        submitButton5.setOpaque(true);
        submitButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                submitButton5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                submitButton5MouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButton5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitButton5MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitButton5MouseEntered(evt);
            }
        });

        signUpButton5.setBackground(new java.awt.Color(255, 255, 255));
        signUpButton5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signUpButton5.setText("Create Account");
        signUpButton5.setOpaque(true);
        signUpButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signUpButton5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signUpButton5MouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpButton5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signUpButton5MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signUpButton5MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(exitButton5)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameLabel5)
                            .addComponent(passLabel5)
                            .addComponent(submitButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(signUpButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passField5)
                            .addComponent(userField5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitButton5)
                .addGap(29, 29, 29)
                .addComponent(usernameLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passField5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signUpButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customer", jPanel4);

        jPanel7.setBackground(new java.awt.Color(237, 151, 157));

        userField6.setOpaque(true);
        userField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userField6userFieldFocusGained(evt);
            }
        });
        userField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userField6ActionPerformed(evt);
            }
        });

        passField6.setOpaque(true);
        passField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passField6passFieldFocusGained(evt);
            }
        });
        passField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passField6passFieldActionPerformed(evt);
            }
        });

        usernameLabel6.setText("User Name");

        passLabel6.setText("Password");

        exitButton6.setText("X");
        exitButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButton6exitButtonMouseClicked(evt);
            }
        });

        submitButton6.setBackground(new java.awt.Color(255, 255, 255));
        submitButton6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        submitButton6.setText("Submit");
        submitButton6.setOpaque(true);
        submitButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                submitButton6submitButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                submitButton6submitButtonMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButton6submitButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitButton6MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitButton6MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(exitButton6)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameLabel6)
                            .addComponent(passLabel6)
                            .addComponent(submitButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passField6)
                            .addComponent(userField6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitButton6)
                .addGap(29, 29, 29)
                .addComponent(usernameLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passField6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signUpButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButton5MouseClicked
        // TODO add your handling code here:
        new signUpPage().setVisible(true);
    }//GEN-LAST:event_signUpButton5MouseClicked

    private void signUpButton5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButton5MouseReleased
        // TODO add your handling code here:
        signUpButton5.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_signUpButton5MouseReleased

    private void signUpButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButton5MousePressed
        // TODO add your handling code here:
        signUpButton5.setBackground(new Color(158, 158, 158));
    }//GEN-LAST:event_signUpButton5MousePressed

    private void submitButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButton5MouseClicked
        // TODO add your handling code here:
        login("users");
    }//GEN-LAST:event_submitButton5MouseClicked

    private void submitButton5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButton5MouseReleased
        // TODO add your handling code here:
        submitButton5.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_submitButton5MouseReleased

    private void submitButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButton5MousePressed
        // TODO add your handling code here:
        submitButton5.setBackground(new Color(158, 158, 158));
    }//GEN-LAST:event_submitButton5MousePressed

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void passField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passField5ActionPerformed
        // TODO add your handling code here:
        login("users");
    }//GEN-LAST:event_passField5ActionPerformed

    private void passField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passField5FocusGained
        // TODO add your handling code here:
        passField5.selectAll();
    }//GEN-LAST:event_passField5FocusGained

    private void userField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userField5FocusGained
        // TODO add your handling code here:
        userField5.selectAll();
    }//GEN-LAST:event_userField5FocusGained

    private void userField6userFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userField6userFieldFocusGained
        // TODO add your handling code here:
        userField6.selectAll();
    }//GEN-LAST:event_userField6userFieldFocusGained

    private void passField6passFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passField6passFieldFocusGained
        // TODO add your handling code here:
        passField6.selectAll();
    }//GEN-LAST:event_passField6passFieldFocusGained

    private void passField6passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passField6passFieldActionPerformed
        // TODO add your handling code here:
        login("admins");
    }//GEN-LAST:event_passField6passFieldActionPerformed

    private void exitButton6exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButton6exitButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButton6exitButtonMouseClicked

    private void submitButton6submitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButton6submitButtonMousePressed
        // TODO add your handling code here:
        login("admins");
    }//GEN-LAST:event_submitButton6submitButtonMousePressed

    private void submitButton6submitButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButton6submitButtonMouseReleased
        // TODO add your handling code here:
        submitButton6.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_submitButton6submitButtonMouseReleased

    private void submitButton6submitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButton6submitButtonMouseClicked
        // TODO add your handling code here:
        login("admins");
    }//GEN-LAST:event_submitButton6submitButtonMouseClicked

    private void submitButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButton5MouseEntered
        // TODO add your handling code here:
        submitButton5.setBackground(new Color(158, 158, 158));
    }//GEN-LAST:event_submitButton5MouseEntered

    private void submitButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButton5MouseExited
        // TODO add your handling code here:
        submitButton5.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_submitButton5MouseExited

    private void signUpButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButton5MouseEntered
        // TODO add your handling code here:
        signUpButton5.setBackground(new Color(158, 158, 158));
    }//GEN-LAST:event_signUpButton5MouseEntered

    private void signUpButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButton5MouseExited
        // TODO add your handling code here:
        signUpButton5.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_signUpButton5MouseExited

    private void submitButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButton6MouseEntered
        // TODO add your handling code here:
        submitButton6.setBackground(new Color(158, 158, 158));
    }//GEN-LAST:event_submitButton6MouseEntered

    private void submitButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButton6MouseExited
        // TODO add your handling code here:
        submitButton6.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_submitButton6MouseExited

    private void userField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userField6ActionPerformed
        // TODO add your handling code here:
        login("users");
    }//GEN-LAST:event_userField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitButton5;
    private javax.swing.JLabel exitButton6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPasswordField passField5;
    private javax.swing.JPasswordField passField6;
    private javax.swing.JLabel passLabel5;
    private javax.swing.JLabel passLabel6;
    private javax.swing.JLabel signUpButton5;
    private javax.swing.JLabel submitButton5;
    private javax.swing.JLabel submitButton6;
    private javax.swing.JTextField userField5;
    private javax.swing.JTextField userField6;
    private javax.swing.JLabel usernameLabel5;
    private javax.swing.JLabel usernameLabel6;
    // End of variables declaration//GEN-END:variables

    public void login(String type) {
        String url = "jdbc:sqlite:test.db";

        try {
            Connection conn = DriverManager.getConnection(url);
            PreparedStatement ps = conn.prepareStatement("select * from " + type + " where username = ? AND password = ?");

            if (type.equals("admins")) {
                ps.setString(1, userField6.getText());
                ps.setString(2, String.valueOf(passField6.getPassword()));
            } else {
                ps.setString(1, userField5.getText());
                ps.setString(2, String.valueOf(passField5.getPassword()));
            }

            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                if (type.equals("admins")) {
                    new mainAdminPage(userField6.getText()).setVisible(true);
                    this.dispose();
                } else {
                    new mainPage(userField5.getText()).setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Incorrect user/pass");
            }

        } catch (SQLException e) {
            System.out.println(e);
        }
    }

}
